# Generated by Django 4.2 on 2026-04-08 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Neurology", "Neurology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("Dermatology", "Dermatology"),
                            ("Psychiatry", "Psychiatry"),
                            ("General", "General Practitioner"),
                            ("Oncology", "Oncology"),
                            ("Gynecology", "Gynecology"),
                            ("Surgery", "General Surgery"),
                        ],
                        max_length=100,
                    ),
                ),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("bio", models.TextField(blank=True)),
                ("years_of_experience", models.IntegerField(default=0)),
                ("qualifications", models.TextField(blank=True)),
                ("clinic_address", models.TextField(blank=True)),
                ("clinic_city", models.CharField(blank=True, max_length=100)),
                ("clinic_state", models.CharField(blank=True, max_length=100)),
                ("clinic_zip", models.CharField(blank=True, max_length=20)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("availability", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["-created_at"],
            },
        ),
    ]
